export default [
	{
		id: 1,
		playerTag: '7973',
		characterName: 'Sig',
		skills: {
			agi: 2,
			for: 2,
			pre: 2,
			vig: 3,
			int: 0,
		},
		attributes: {
			acrobacia: 0,
			adestramento: 0,
			artes: 0,
			atletismo: 5,
			atualidades: 0,
			ciencias: 0,
			crime: 0,
			diplomacia: 0,
			enganacao: 0,
			fortitude: 5,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 5,
			investigacao: 0,
			luta: 5,
			medicina: 0,
			ocultismo: 0,
			percepcao: 0,
			pilotagem: 0,
			pontaria: 5,
			profissao: 0,
			reflexos: 5,
			religiao: 0,
			sobrevivencia: 0,
			tatica: 0,
			tecnologia: 0,
			vontade: 0,
		},
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
			{
				name: 'revolver',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d6',
				damageType: 'balistico',
			},
			{
				name: 'Katana',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d10',
				damageType: 'cortante',
			},
		],
	},
	{
		id: 2,
		playerTag: '8008',
		characterName: 'Noah',
		skills: {
			agi: 2,
			for: 0,
			pre: 2,
			vig: 2,
			int: 3,
		},
		attributes: {
			acrobacia: 5,
			adestramento: 0,
			artes: 0,
			atletismo: 0,
			atualidades: 5,
			ciencias: 5,
			crime: 5,
			diplomacia: 0,
			enganacao: 0,
			fortitude: 0,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 0,
			investigacao: 5,
			luta: 0,
			medicina: 10,
			ocultismo: 5,
			percepcao: 5,
			pilotagem: 0,
			pontaria: 0,
			profissao: 5,
			reflexos: 0,
			religiao: 5,
			sobrevivencia: 0,
			tatica: 0,
			tecnologia: 0,
			vontade: 0,
		},
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
			{
				name: 'pistola',
				type: 'distancia',
				critical: '18',
				damageDice: '1d12',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 3,
		playerTag: '9837',
		characterName: 'Nikolai',
		skills: {
			agi: 3,
			for: 3,
			pre: 0,
			vig: 2,
			int: 1,
		},
		attributes: {
			acrobacia: 0,
			adestramento: 0,
			artes: 0,
			atletismo: 0,
			atualidades: 0,
			ciencias: 0,
			crime: 0,
			diplomacia: 0,
			enganacao: 0,
			fortitude: 0,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 0,
			investigacao: 0,
			luta: 5,
			medicina: 0,
			ocultismo: 0,
			percepcao: 0,
			pilotagem: 0,
			pontaria: 12,
			profissao: 0,
			reflexos: 5,
			religiao: 0,
			sobrevivencia: 0,
			tatica: 5,
			tecnologia: 0,
			vontade: 0,
		},
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
			{
				name: 'revolver',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d6',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de assalto',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d10',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 4,
		playerTag: '2840',
		characterName: 'Augusto',
		skills: {
			agi: 2,
			for: 1,
			pre: 2,
			vig: 2,
			int: 3,
		},
		attributes: {
			acrobacia: 0,
			adestramento: 0,
			artes: 0,
			atletismo: 0,
			atualidades: 0,
			ciencias: 10,
			crime: 0,
			diplomacia: 5,
			enganacao: 5,
			fortitude: 0,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 5,
			investigacao: 10,
			luta: 0,
			medicina: 0,
			ocultismo: 5,
			percepcao: 5,
			pilotagem: 0,
			pontaria: 5,
			profissao: 0,
			reflexos: 0,
			religiao: 5,
			sobrevivencia: 0,
			tatica: 0,
			tecnologia: 0,
			vontade: 0,
		},
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
			{
				name: 'pistola',
				type: 'distancia',
				critical: '18',
				damageDice: '1d12',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 5,
		playerTag: '8804',
		characterName: 'Perikles',
		skills: {
			agi: 2,
			for: 2,
			pre: 1,
			vig: 2,
			int: 3,
		},
		attributes: {
			acrobacia: 0,
			adestramento: 0,
			artes: 0,
			atletismo: 0,
			atualidades: 0,
			ciencias: 0,
			crime: 0,
			diplomacia: 0,
			enganacao: 0,
			fortitude: 5,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 0,
			investigacao: 5,
			luta: 5,
			medicina: 5,
			ocultismo: 10,
			percepcao: 0,
			pilotagem: 5,
			pontaria: 5,
			profissao: 0,
			reflexos: 5,
			religiao: 0,
			sobrevivencia: 0,
			tatica: 5,
			tecnologia: 0,
			vontade: 5,
		},
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
			{
				name: 'revolver',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d6',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 6,
		playerTag: '2576',
		characterName: 'Samuel',
		skills: {
			for: 1,
			agi: 2,
			pre: 2,
			vig: 1,
			int: 3,
		},
		attributes: {
			acrobacia: 5,
			adestramento: 0,
			artes: 0,
			atletismo: 5,
			atualidades: 0,
			ciencias: 0,
			crime: 0,
			diplomacia: 0,
			enganacao: 0,
			fortitude: 0,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 5,
			intuicao: 0,
			investigacao: 5,
			luta: 5,
			medicina: 0,
			ocultismo: 5,
			percepcao: 5,
			pilotagem: 0,
			pontaria: 0,
			profissao: 0,
			reflexos: 5,
			religiao: 5,
			sobrevivencia: 0,
			tatica: 0,
			tecnologia: 0,
			vontade: 10,
		},
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
			{
				name: 'pistola',
				type: 'distancia',
				critical: '18',
				damageDice: '1d12',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 7,
		playerTag: '8831',
		characterName: 'Sara Linn',
		skills: {
			for: 1,
			agi: 2,
			pre: 2,
			vig: 1,
			int: 3,
		},
		attributes: {
			acrobacia: 0,
			adestramento: 0,
			artes: 10,
			atletismo: 0,
			atualidades: 0,
			ciencias: 0,
			crime: 0,
			diplomacia: 10,
			enganacao: 0,
			fortitude: 0,
			furtividade: 0,
			iniciativa: 0,
			intimidacao: 0,
			intuicao: 10,
			investigacao: 0,
			luta: 0,
			medicina: 0,
			ocultismo: 0,
			percepcao: 10,
			pilotagem: 0,
			pontaria: 10,
			profissao: 0,
			reflexos: 0,
			religiao: 0,
			sobrevivencia: 0,
			tatica: 0,
			tecnologia: 10,
			vontade: 0,
		},
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
			{
				name: 'revolver',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d6',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
];
