export default [
	{
		id: 1,
		playerTag: '7973',
		characterName: 'player1',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tática'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
		],
	},
	{
		id: 2,
		playerTag: '8008',
		characterName: 'player2',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
		],
	},
	{
		id: 3,
		playerTag: '9837',
		characterName: 'player3',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
		],
	},
	{
		id: 4,
		playerTag: '2840',
		characterName: 'player4',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
		],
	},
	{
		id: 5,
		playerTag: '8804',
		characterName: 'player5',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
			{
				name: 'revolver',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d6',
				damageType: 'balistico',
			},
			{
				name: 'fuzil de caça',
				type: 'distancia',
				critical: '19x3',
				damageDice: '2d8',
				damageType: 'balistico',
			},
		],
	},
	{
		id: 6,
		playerTag: '2576',
		characterName: 'player7',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'faca',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
		],
	},
	{
		id: 7,
		playerTag: '8831',
		characterName: 'test',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'inteligência'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'punhal',
				type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
		],
	},
];
