export default [
	{
		playerTag: '350366358879338496',
		characterName: 'Diego',
		skills: [
			{value: 1, name: 'agilidade'},
			{value: 2, name: 'força'},
			{value: 2, name: 'presença'},
			{value: 2, name: 'vigor'},
			{value: 2, name: 'intelecto'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 2, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 7, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 7, name: 'investigação'},
			{value: 5, name: 'luta'},
			{value: 5, name: 'medicina'},
			{value: 5, name: 'ocultismo'},
			{value: 5, name: 'percepção'},
			{value: 5, name: 'pilotagem'},
			{value: 5, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 5, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 5, name: 'sobrevivência'},
			{value: 0, name: 'tática'},
			{value: 0, name: 'tecnologia'},
			{value: 5, name: 'vontade'},
		],
		weapons: [
			{
				name: 'katana',
				weapon_type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d10',
				damageType: 'perfurante',
			},
			{
				name: 'bastão',
				weapon_type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d8',
				damageType: 'impacto',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '317038533770608643',
		characterName: 'Alex',
		skills: [
			{value: 1, name: 'agilidade'},
			{value: 2, name: 'força'},
			{value: 2, name: 'presença'},
			{value: 1, name: 'vigor'},
			{value: 3, name: 'intelecto'},
		],
		attributes: [
			{value: 5, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 5, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 7, name: 'diplomacia'},
			{value: 5, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 5, name: 'intuição'},
			{value: 7, name: 'investigação'},
			{value: 5, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 5, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 7, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 5, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 5, name: 'vontade'},
		],
		weapons: [
			{
				name: 'martelo',
				weapon_type: 'corpo a corpo',
				critical: '20',
				damageDice: '1d6',
				damageType: 'impacto',
			},
			{
				name: 'cajado',
				weapon_type: 'corpo a corpo',
				critical: '20',
				damageDice: '1d6',
				damageType: 'impacto',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '7206',
		characterName: 'gonzales',
		skills: [
			{value: 1, name: 'agilidade'},
			{value: 3, name: 'força'},
			{value: 1, name: 'presença'},
			{value: 1, name: 'vigor'},
			{value: 3, name: 'intelecto'},
		],
		attributes: [
			{value: 2, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 2, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 5, name: 'investigação'},
			{value: 5, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 5, name: 'ocultismo'},
			{value: 5, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 5, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 5, name: 'reflexos'},
			{value: 5, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 5, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 5, name: 'vontade'},
		],
		weapons: [
			{
				name: 'pistola',
				weapon_type: 'distancia',
				critical: '19',
				damageDice: '1d12',
				damageType: 'balistico',
			},
			{
				name: 'coronhada',
				weapon_type: 'corpo a corpo',
				critical: '20',
				damageDice: '1d4',
				damageType: 'impacto',
			},
			{
				name: 'bastão',
				weapon_type: 'corpo a corpo',
				critical: '20',
				damageDice: '1d8',
				damageType: 'impacto',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '287238243068411904',
		characterName: 'Thiago',
		skills: [
			{value: 1, name: 'agilidade'},
			{value: 2, name: 'força'},
			{value: 2, name: 'presença'},
			{value: 2, name: 'vigor'},
			{value: 2, name: 'intelecto'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 5, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 5, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 5, name: 'intuição'},
			{value: 7, name: 'investigação'},
			{value: 5, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 7, name: 'ocultismo'},
			{value: 7, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 5, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 5, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 5, name: 'vontade'},
		],
		weapons: [
			{
				name: 'cajado',
				weapon_type: 'corpo a corpo',
				critical: 'x2',
				damageDice: '1d6',
				damageType: 'impacto',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '315259927230676993',
		characterName: 'Rui Armando',
		skills: [
			{value: 1, name: 'agilidade'},
			{value: 3, name: 'força'},
			{value: 2, name: 'presença'},
			{value: 2, name: 'vigor'},
			{value: 1, name: 'intelecto'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 5, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 5, name: 'iniciativa'},
			{value: 2, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 5, name: 'investigação'},
			{value: 5, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 2, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 5, name: 'profissão'},
			{value: 5, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 5, name: 'vontade'},
		],
		weapons: [
			{
				name: 'marreta',
				weapon_type: 'corpo a corpo',
				critical: '19',
				damageDice: '3d4',
				damageType: 'perfurante',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '2576',
		characterName: 'player7',
		skills: [
			{value: 0, name: 'agilidade'},
			{value: 0, name: 'força'},
			{value: 0, name: 'presença'},
			{value: 0, name: 'vigor'},
			{value: 0, name: 'intelecto'},
		],
		attributes: [
			{value: 0, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 0, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 0, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 0, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 0, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 0, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'faca',
				weapon_type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'cortante',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
	{
		playerTag: '391540664376098817',
		characterName: 'test',
		skills: [
			{value: 5, name: 'agilidade'},
			{value: 4, name: 'força'},
			{value: 2, name: 'presença'},
			{value: 4, name: 'vigor'},
			{value: 3, name: 'intelecto'},
		],
		attributes: [
			{value: 2, name: 'acrobacia'},
			{value: 0, name: 'adestramento'},
			{value: 0, name: 'artes'},
			{value: 0, name: 'atletismo'},
			{value: 0, name: 'atualidades'},
			{value: 0, name: 'ciências'},
			{value: 5, name: 'crime'},
			{value: 0, name: 'diplomacia'},
			{value: 0, name: 'enganação'},
			{value: 5, name: 'fortitude'},
			{value: 0, name: 'furtividade'},
			{value: 0, name: 'iniciativa'},
			{value: 0, name: 'intimidação'},
			{value: 0, name: 'intuição'},
			{value: 0, name: 'investigação'},
			{value: 7, name: 'luta'},
			{value: 0, name: 'medicina'},
			{value: 0, name: 'ocultismo'},
			{value: 0, name: 'percepção'},
			{value: 0, name: 'pilotagem'},
			{value: 0, name: 'pontaria'},
			{value: 5, name: 'profissão'},
			{value: 0, name: 'reflexos'},
			{value: 5, name: 'religião'},
			{value: 0, name: 'sobrevivência'},
			{value: 0, name: 'tatica'},
			{value: 0, name: 'tecnologia'},
			{value: 0, name: 'vontade'},
		],
		weapons: [
			{
				name: 'punhal',
				weapon_type: 'corpo a corpo',
				critical: '19',
				damageDice: '1d4',
				damageType: 'perfurante',
			},
		],
		dmTag: '8831',
		attacks: [],
		habilities: [],
		origin: '',
		characterClass: '',
		nex: '',
		movement: '',
		pv: '',
		pe: '',
		pvMax: '',
		peMax: '',
		defense: '',
		sanity: '',
		protection: '',
		resistance: '',
	},
];
